name: Royal Carribean Cruise deployment gates workflow
on:
  workflow_dispatch:
jobs:

  prestuff:
    name: Pre-Stuff
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: echo true

  change:
    name: ServiceNow DevOps Change
    needs: prestuff
    runs-on: ubuntu-latest
    outputs:
      change-request-number: ${{ steps.change.outputs.change-request-number }}
    steps:
    - name: Pretest
      run: echo False

    - name: ServiceNow DevOps Change Attributes
      uses: ServiceNow/servicenow-devops-change@v4.1.0
      with:
        devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ toJSON(github) }}
        job-name: 'ServiceNow DevOps Change'
        change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
        interval: '100'
        timeout: '3600'
        deployment-gate: '{"environment":"rama_deployment_gate","jobId": "deploy", "jobName":"Deploy"}'

  deploy:
    name: Deploy
    environment: rama_deployment_gate
    needs: change
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo true
